#!/usr/bin/env bash
#-*-coding:utf-8 -*-
#Auto updated?
#   Yes
#File:
#   SetupPopOs
#Author:
#   HeCodes2Much [wayne6324@gmail.com]
#Github:
#   https://github.com/HeCodes2Much/
#
#Created:
#   Fri 02 August 2024, 04:18:40 PM [GMT+1]
#Modified:
#   Fri 02 August 2024, 04:22:22 PM [GMT+1]
#
#Description:
#   Setup Github PopOS DotFiles
#
#Dependencies:
#   Git
#

# Clone the dotfiles repository
git clone git@github.com:HeCodes2Much/DotFiles_PopOS.git ~/.DotFiles

# Copy dotfiles to home directory
cp ~/.dotfiles/.bashrc ~/.bashrc
# cp ~/.dotfiles/.vimrc ~/.vimrc
# Repeat for other dotfiles...

# Source the new bashrc
source ~/.bashrc
